### ISSUE TITLE
T - Foundational work for CSS refactor

### ISSUE THREAD

**Issue by tobinmori** [mdn/mdn-minimalist#31]
**Acceptance Criteria**
- [ ] Grid complete
- [ ] base styles implemented
- [ ] styles for focus/active improved

**Comment by malqinneh** [comment]
Added https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/234 and included action items from this ticket to it. This user story can be closed @schalkneethling, let me know what you think.

**Comment by tobinmori** [comment]
Closing as irrelevant because more specific stories cover this.
