### ISSUE TITLE
Not sure on line breck here because code

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#348]
![Screenshot_20201209-234002.png](https://user-images.githubusercontent.com/44380480/101697363-fcb26100-3a77-11eb-9402-c34ff0abd147.png)

**Comment by schalkneethling** [comment]
It is not ideal for sure but, until we have had time to invest in how we display tables such as these on mobile, it is a necesarry stop gap to avoid horizontal scroll.

**Comment by mattiapontonio** [comment]
It seems that horizontal scrolling is a good solution but it also seems that you have to ask for a wrapper from React.
