### ISSUE TITLE
Update properties table for better color contrast

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#351]
https://developer.allizom.org/en-US/docs/Web/HTML/Element/input/search
![Screenshot_20201210-171157.png](https://user-images.githubusercontent.com/44380480/101798214-2799c500-3b0b-11eb-9c2c-59fc2f354eed.png)

**Comment by schalkneethling** [comment]
![Screenshot 2020-12-13 at 06 52 49](https://user-images.githubusercontent.com/10350960/102003411-d27ad080-3d0f-11eb-9802-d372ef94f1f7.png)

Table colors to be updated to the above

**Comment by mattiapontonio** [comment]
Much less conflicting opinions and more the table 🙂👍
