### ISSUE TITLE
atom for pre (pre.scss)

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#352]
Sorry if not PR.
I'm Just looking a little bit at the code.

![Screenshot_20201210-204309.png](https://user-images.githubusercontent.com/44380480/101821668-8de11080-3b28-11eb-8dbc-7fc7afeb4065.png)

**Comment by schalkneethling** [comment]
@mattiapontonio This is always tricky and I am constantly rethinkig this. Technically we can have:

- _pre.scss
- _code.scss
- _kbd.scss

and maybe we should. It does make sense in terms of the concepts around atoms. Thanks for mentioning this.

**Comment by mattiapontonio** [comment]
@schalkneethling 

That's right, I think it's a good idea. Sass is good but it is better to try to align with the tags, otherwise it could soon get complicated.

**Comment by mattiapontonio** [comment]
@schalkneethling thanks!
