### ISSUE TITLE
atoms/kbd.scss

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#353]
![Screenshot_20201210-204848.png](https://user-images.githubusercontent.com/44380480/101822146-2ecfcb80-3b29-11eb-8ab6-3300f36cefab.png)

**Comment by schalkneethling** [comment]
As mentioned in https://github.com/mdn/mdn-minimalist/issues/352#issuecomment-742756454 - this makes sense. Closng as duplicate
