### ISSUE TITLE
These should be duplicates (not-DRY) inside the atoms that need it (pre and or code?)

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#355]
![Screenshot_20201211-000621.png](https://user-images.githubusercontent.com/44380480/101840806-153c7d00-3b45-11eb-98f0-c68d6ee19518.png)

## Compiled

```css
pre.bad {}
pre.good {}
code.bad {}
code.good {}
```

Why 2? It is necessary to understand in the project if there are only bad `code`s or even bad `pre`spaced ones.

**Comment by schalkneethling** [comment]
I believe not having it tied to a specific element type, provides a bit more freedom and works for now.
