### ISSUE TITLE
indentation to 1 space

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/mdn-minimalist#426]
For me that indent with a smartphone and a keyboard mobile in a text area without terminal 👍

**Comment by mattiapontonio** [comment]
https://github.com/mdn/mdn-minimalist/pull/425

**Comment by schalkneethling** [comment]
> For me that indent with a smartphone and a keyboard mobile in a text area without terminal 👍

I am not sure I understand what you are referring to here. Could you add some additional details?

**Comment by mattiapontonio** [comment]
Is possibile to indent like this?
Is this the error with the action?
https://github.com/mdn/mdn-minimalist/pull/425/checks

![Screenshot_20210117-181410.png](https://user-images.githubusercontent.com/44380480/104850523-f1144e80-58ef-11eb-8321-b51b93466eab.png)

**Comment by mattiapontonio** [comment]
https://www.github.com/mdn/mdn-minimalist/tree/main/.stylelintrc.json

**Comment by schalkneethling** [comment]
Ah, I see. It is of course possible, but we have standardized on whatever is the default for Prettier(https://prettier.io). By doing this, we create consistency across codebases and free up some brain cells to use for other more interesting things 😃 

Thank you for asking and clarifying though.

**Comment by mattiapontonio** [comment]
I Need some brain allocation for sort interest mine and of the others 🙂
Anyway make sense, better don't talking too much on style, even cose style 👍
