### ISSUE TITLE
Do we need a specific style for callout-box

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-minimalist#440]
See https://github.com/mdn/yari/issues/2158 where this was originally reported.

I wonder if we need an additional style for these or whether we can reuse something like the notecards here? I did a search across the current content repo for `callout-box`, and it is currently 14 matches in 13 files.

It feels like a situation where, even if it is a small amount of CSS, it might not be worth continuing to support this component style. @chrisdavidmills I would appreciate your thoughts on this. Thank you

**Comment by chrisdavidmills** [comment]
I have literally never used one of these callouts in my time on MDN, not once. To me, conceptually, the callout box is kind of akin to the pull quotes you get in magazine layouts. I don't see us needing those on MDN really, plus looking at the content in those callouts I reckon they could just be note cards instead (which I think @mattiapontonio suggested?), allowing us to simplify the component base.

Two more reasons not to bother with them:

1. more challenging to represent them in the layout across dektop and mobile (floated box versus just another box that sits in the main content column)
2. more specialist styles means more of a challenge when we start to make the move to markdown.

**Comment by mattiapontonio** [comment]
> allowing us to simplify the component base

Self-care 🛀🚿👍

**Comment by schalkneethling** [comment]
Thank you @chrisdavidmills - I will go ahead and update the content on those pages to use notecards.

**Comment by schalkneethling** [comment]
Being addressed here: https://github.com/mdn/content/issues/1660

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/content/pull/1661
