### ISSUE TITLE
Consider the use of a mixin in notecards

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-minimalist#456]
> Instead of repeating blocks in notecards (and only changing value of background image) - couldn't that be a mixin or function or smth?

Received the above comment on Twitter from @Ryuno-Ki - It is a really nice idea to consider.

**Comment by Ryuno-Ki** [comment]
Thanks for you twitch-stream today, @schalkneethling!
The idea was to reduce some repetition in

https://github.com/mdn/mdn-minimalist/blob/94bbc4b729a767e7b763762db4872686449a1047/sass/atoms/_notecards.scss#L83-L188

(I could only tell from glancing over the streamed code view).

**Comment by schalkneethling** [comment]
Closed by https://github.com/mdn/mdn-minimalist/pull/504
