### ISSUE TITLE
There's no need for `.notecard h2`

### ISSUE THREAD

**Issue by peterbe** [mdn/mdn-minimalist#470]
In all the active content, there's never a `.notecard h2`, 
See https://github.com/mdn/yari/issues/2793
So all selectors, like `.notecard.deprecated h2` are never used. We can delete that.

**Comment by peterbe** [comment]
Wow. That welcome message is loud.

**Comment by schalkneethling** [comment]
> Wow. That welcome message is loud.

:) Thanks for testing it out.

**Comment by schalkneethling** [comment]
> In all the active content, there's never a `.notecard h2`,
> See [mdn/yari#2793](https://github.com/mdn/yari/issues/2793)
> So all selectors, like `.notecard.deprecated h2` are never used. We can delete that.

Technically we won't and should not but, I ran into a potential use case here:
https://github.com/mdn/content/pull/1661#pullrequestreview-586194162

With that said, using either an `h2` or `h3` inside that notecard causes Yari to extract it from the notecard and add it to its own "line" in the DOM. Once the `h1` is a natural part of `main` element and thus content, we will never have a document that has a notecard as the very first item. Even then, a document structure of

h1 Strict mode
-- h2 Strict Mode Overview
---- h3 Note

would be preferable over 

h1 Strict mode
-- h2 Note

Although not technically incorrect. With that mouth full, let's keep `h2` for now but yes, we might end up never needing it.
