### ISSUE TITLE
Issue with "HTML elements reference": Element names linebreak with hyphens

### ISSUE THREAD

**Issue by phoenixeliot** [mdn/mdn-minimalist#531]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

#### What information was incorrect, unhelpful, or incomplete?
The first column isn't wide enough, which causes some items to be line-broken with hyphens, which is misleading about the tag names. The column should be made wide enough when possible, and we should consider removing `word-wrap: break-word;` from the `code` blocks used there.

#### Specific section or headline?
Text content
Embedded content
Scripting

#### What did you expect to see?
`<figcaption>`
`<figure>`
`<picture>`
`<noscript>`

#### Actually seen:
```
<fig-
caption
>
```

```
<figure
>
```

```
<picture
>
```

```
<no-
script>
```

#### Did you test this? If so, how?
Visual check on the page.
<img width="944" alt="Screen Shot 2021-03-09 at 8 02 29 PM" src="https://user-images.githubusercontent.com/491376/110569934-6b07cd80-8112-11eb-9eb8-3fe63918a665.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/index.html
* Last commit: https://github.com/mdn/content/commit/c40f133b4ed8474730029e68a397aaebb042266b
* Document last modified: 2021-03-01T15:30:53.000Z

</details>

**Comment by schalkneethling** [comment]
@phoenixeliot @chrisdavidmills We recently made a change that I believe resolved this issue. Could one of you confirm? Thank you!

**Comment by phoenixeliot** [comment]
Looks good! Couldn't get them to collapse at any size/zoom.

**Comment by schalkneethling** [comment]
> Looks good! Couldn't get them to collapse at any size/zoom.

Thank you for the super fast reply @phoenixeliot, much appreciated.
