### ISSUE TITLE
💡 Switch the SASS module system

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-minimalist#55]
We should switch to using the SASS module system instead of `@import`. For details see:
https://sass-lang.com/blog/the-module-system-is-launched

**Comment by imme-emosol** [comment]
For reference/guide: https://github.com/mdn/mdn-minimalist/search?l=SCSS&q=import .

Any thoughts/guidelines for the namespaces? Probably use `@forward` in mdn-minimalist.scss ?
( typing `mdn-web-docs-palette.mdn-neutral100` seems elaborate )

**Comment by schalkneethling** [comment]
> For reference/guide: https://github.com/mdn/mdn-minimalist/search?l=SCSS&q=import .
> 
> Any thoughts/guidelines for the namespaces? Probably use `@forward` in mdn-minimalist.scss ?
> ( typing `mdn-web-docs-palette.mdn-neutral100` seems elaborate )

That is interesting. I am thinking using `@forward` makes sense within the main minimalist SASS file[https://github.com/mdn/mdn-minimalist/blob/125d88afe74c24b83f9788d4feadc11d377a62d4/sass/mdn-minimalist.scss] but, perhaps using `@use` would be the way to go for individual SASS files like https://github.com/mdn/mdn-minimalist/blob/125d88afe74c24b83f9788d4feadc11d377a62d4/sass/atoms/_buttons.scss

What do you think?

**Comment by schalkneethling** [comment]
Doh! I think what I stated above is what you meant in your comment 😄

**Comment by schalkneethling** [comment]
Yes! We definitely want to use `@forward` inside `mdn-minimalist.scss`. You can then either do:

```
@use "~@mdn/minimalist/mdn-minimalist";

body {
  background-color: mdn-minimalist.$neutral100;
}
```

or,

```
@use "~@mdn/minimalist/mdn-minimalist" as *;

body {
  background-color: $neutral100;
}
```

**Comment by schalkneethling** [comment]
The other BIG change for the library itself is that each module needs to import what it needs directly. Relying on everything that is imported in `mdn-minimalist` will not work. In this instance I reckon just using the implicit namespace makes sense as this addresses one of the problems that was identified with using `@import` i.e.

> It was next to impossible to figure out where a given variable, mixin, or function (collectively called “members”) was originally defined, since anything defined in one stylesheet was available to all stylesheets that were imported after it.

That also means one can be more selective with what you `@forward` in `mdn-minimalist`
