### ISSUE TITLE
SVG icon in footer is missing 'icon' class

### ISSUE THREAD

**Issue by tannerdolby** [mdn/mdn-minimalist#725]
I noticed that when heading over to https://mdn-minimalist.netlify.app/tables/ there are some fonts not being loaded in (shown in console) and it looks some styles aren't around, specifically the footer. I'm not sure if the overhaul to `@use` had anything to do with this, considering all the tests passed, I don't think the overhaul is contributing to this issue. Also the GitHub svg didn't have the `.icon` class so its dimensions are blown up, for the sake of the screenshot I added it into the markup through dev tools.

I'm happy to help fix anything that was caused by the overahaul to `@use` (which I don't think is the problem but could be). Let me know your thoughts! @schalkneethling 

<img width="1267" alt="Screen Shot 2021-08-02 at 9 12 17 AM" src="https://user-images.githubusercontent.com/48612525/127892305-177ef046-ddde-47d0-b2fb-9c7ef96b3f47.png">

**Comment by tannerdolby** [comment]
The above screenshot doesn't really show the issue since I changed markup adding the missing `.icon` class to the svg, here is the current home page with the oversized GitHub icon

<img width="1254" alt="Screen Shot 2021-08-16 at 7 18 10 PM" src="https://user-images.githubusercontent.com/48612525/129653438-76776e20-576c-4027-a46a-8d5752321179.png">

**Comment by tannerdolby** [comment]
The UI looks a bit wonky with the GitHub icon still extremely large in size. Let me know if you need me to tackle anything here.

ping @schalkneethling

**Comment by schalkneethling** [comment]
> The UI looks a bit wonky with the GitHub icon still extremely large in size. Let me know if you need me to tackle anything here.
> 
> ping @schalkneethling

You are definitely more than welcome to take this one if you want @tannerdolby 🙏

**Comment by tannerdolby** [comment]
> You are definitely more than welcome to take this one if you want @tannerdolby 🙏

Ok deal. I will take this on and provide some fixes in the next few days. Thanks @schalkneethling !
