### ISSUE TITLE
Fix the docs website UI 

### ISSUE THREAD

**Issue by amm834** [mdn/mdn-minimalist#748]
When I read the docs of mdn css doc, it is not good to read with mobile device. Please fix it.

![Screenshot_2021-08-30-13-56-46-22_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/65492233/131302037-55811265-748b-4e2c-b4dc-40c4ae808c26.jpg)

**Comment by teoli2003** [comment]
Hi, what is the url? And what browser are you using?

**Comment by amm834** [comment]
**Url**
https://mdn-minimalist.netlify.app/
I'm using chrome Android browser.

**Comment by schalkneethling** [comment]
Thank you for reporting @amm834. This is a duplicate of https://github.com/mdn/mdn-minimalist/issues/725 so closing as a duplicate. We will definitely address this but, there are a couple of more pressing items we need to address first.
