### ISSUE TITLE
Display MDN web docs' dev toolbar on any display width

### ISSUE THREAD

**Issue by queengooborg** [mdn/mdn-minimalist#795]
The buttons to open the editor, show flaws, etc. are set to hide on smaller display widths, same as the sidebar. However, on my laptop when setting the window to half-width (of which I set windows to often), this media query gets in the way and hides these elements. This seems odd considering my screen's pixel count is quite high plus retina. Due to this, I feel that we should eliminate this media query and show the toolbar on any width.

**Comment by tannerdolby** [comment]
@queengooborg I'm for this as well!

**Comment by queengooborg** [comment]
Apparently this is also something controlled directly within Yari -- opening a PR now!
